//! # hsmc
//!
//! Hierarchical state machines (statecharts) with a declarative proc-macro front-end.
//!
//! See the crate's spec (`docs/000. original-hsmc-spec.md`) for v0.1 semantics
//! and the top-level README for the v0.2 additions (`during:`, optional
//! `events:`, `dispatch()`, `STATE_CHART`).
//!
//! ## Macro invocation syntax
//!
//! The `statechart!` macro uses Rust's standard proc-macro call syntax —
//! the machine name goes *inside* the outer brace/parenthesis, because Rust
//! does not permit tokens between `!` and the macro delimiter:
//!
//! ```ignore
//! use hsmc::{statechart, Duration};
//!
//! # #[derive(Default)] struct MyContext;
//! # #[derive(Debug, Clone)] enum MyEvent { Go }
//! statechart! {
//!     MyMachine {
//!         context: MyContext;
//!         events:  MyEvent;
//!         default(Idle);
//!         state Idle { on(Go) => Busy; }
//!         state Busy { }
//!     }
//! }
//! ```
//!
//! ## `during:` activities (v0.2)
//!
//! Any state can declare one or more `during:` activities — async functions
//! that run while the state is on the active path and produce events:
//!
//! ```ignore
//! state Receiving {
//!     during: next_packet(lora, rx_buf);
//!     on(PacketRx { rssi: i16 }) => count_packet;
//!     on(StopRx) => Idle;
//! }
//!
//! async fn next_packet(lora: &mut LoRaDriver, buf: &mut [u8; 256]) -> Ev {
//!     lora.rx(buf).await.into()
//! }
//! ```
//!
//! The macro emits `next_packet(&mut ctx.lora, &mut ctx.rx_buf)` in the
//! generated run loop's `select` call, and Rust's native split-borrow
//! verifies at compile time that concurrent durings don't borrow
//! overlapping fields.
//!
//! ### Cancel-safety contract
//!
//! A `during:` future **will** be dropped at any `.await` point whenever a
//! handler fires, a timer expires, an external event arrives, or the state
//! transitions. Write durings as cancel-safe state machines: every `.await`
//! must be a clean resume point where dropping the future leaves borrowed
//! fields in a valid, re-enterable state. Prefer performing mutations
//! *after* awaited I/O completes rather than straddling await points.
//!
//! ## A note on `unexpected_cfgs` warnings
//!
//! The code emitted by `statechart!` contains `#[cfg(feature = "tokio")]` /
//! `#[cfg(feature = "embassy")]` gates so that feature-specific items (the
//! `Sender`, `run()`) compile only under the matching feature of the `hsmc`
//! crate. Rust 1.80+ `check-cfg` evaluates those attributes in the context
//! of the *calling* crate — so if your crate doesn't itself declare features
//! named `tokio` or `embassy`, rustc will emit `unexpected_cfgs` warnings at
//! every `statechart!` invocation. To silence them, add either:
//!
//! ```ignore
//! #![allow(unexpected_cfgs)]   // at the crate root, or
//! ```
//!
//! or, in your `Cargo.toml`:
//!
//! ```toml
//! [lints.rust]
//! unexpected_cfgs = { level = "allow", check-cfg = ['cfg(feature, values("tokio", "embassy"))'] }
//! ```
//!
//! This is a known limitation of proc-macros that emit cfg-gated code.
//!
//! ## Out of scope (spec §11)
//!
//! The following are explicitly NOT part of v0.1 and should not be added
//! without revisiting the spec: guard conditions, orthogonal / parallel
//! regions, history states (shallow or deep), deferred events, internal
//! transitions, state-local context / per-state data, visual rendering or
//! diagram export, runtime statechart modification, event priorities beyond
//! FIFO, and inter-machine communication primitives.

#![cfg_attr(not(any(test, feature = "tokio")), no_std)]

#[cfg(all(feature = "tokio", feature = "embassy"))]
compile_error!("hsmc features `tokio` and `embassy` are mutually exclusive");

pub use core::time::Duration;
pub use hsmc_macros::statechart;

mod error;
pub use error::HsmcError;

#[doc(hidden)]
pub mod __private {
    //! Implementation details used by code generated by the `statechart!` macro.
    //! Not part of the public API.
    pub use heapless;

    pub use crate::error::HsmcError;

    /// A simple bounded event queue built on `heapless::Deque`.
    /// Capacity is a const generic.
    pub struct EventQueue<E, const N: usize> {
        inner: heapless::Deque<E, N>,
    }

    impl<E, const N: usize> EventQueue<E, N> {
        pub const fn new() -> Self {
            Self {
                inner: heapless::Deque::new(),
            }
        }
        pub fn push(&mut self, ev: E) -> Result<(), HsmcError> {
            self.inner.push_back(ev).map_err(|_| HsmcError::QueueFull)
        }
        pub fn pop(&mut self) -> Option<E> {
            self.inner.pop_front()
        }
        pub fn is_empty(&self) -> bool {
            self.inner.is_empty()
        }
        pub fn clear(&mut self) {
            while self.inner.pop_front().is_some() {}
        }
    }

    impl<E, const N: usize> Default for EventQueue<E, N> {
        fn default() -> Self {
            Self::new()
        }
    }

    /// A fixed-capacity timer table: `(state_index, trigger_index, remaining_nanos)`.
    pub struct TimerTable<const N: usize> {
        pub entries: heapless::Vec<TimerEntry, N>,
    }

    #[derive(Clone, Copy, Debug)]
    pub struct TimerEntry {
        pub state: u16,
        pub trigger: u16,
        pub remaining_ns: u128,
    }

    impl<const N: usize> Default for TimerTable<N> {
        fn default() -> Self {
            Self::new()
        }
    }

    impl<const N: usize> TimerTable<N> {
        pub const fn new() -> Self {
            Self {
                entries: heapless::Vec::new(),
            }
        }
        pub fn start(&mut self, state: u16, trigger: u16, duration: core::time::Duration) {
            let ns = duration.as_nanos();
            // Replace existing entry for same (state, trigger) — resets on re-entry.
            for e in self.entries.iter_mut() {
                if e.state == state && e.trigger == trigger {
                    e.remaining_ns = ns;
                    return;
                }
            }
            let _ = self.entries.push(TimerEntry {
                state,
                trigger,
                remaining_ns: ns,
            });
        }
        pub fn cancel_state(&mut self, state: u16) {
            self.entries.retain(|e| e.state != state);
        }
        pub fn cancel_one(&mut self, state: u16, trigger: u16) {
            self.entries
                .retain(|e| !(e.state == state && e.trigger == trigger));
        }
        pub fn decrement(&mut self, elapsed: core::time::Duration) {
            let ns = elapsed.as_nanos();
            for e in self.entries.iter_mut() {
                e.remaining_ns = e.remaining_ns.saturating_sub(ns);
            }
        }
        /// Returns (state, trigger) of first expired timer, picking the innermost
        /// (deepest) state, ties broken by declaration order.
        pub fn pop_expired(&mut self, depth: &[u8]) -> Option<(u16, u16)> {
            let mut best: Option<usize> = None;
            for (i, e) in self.entries.iter().enumerate() {
                if e.remaining_ns == 0 {
                    match best {
                        None => best = Some(i),
                        Some(bi) => {
                            let cur = depth[e.state as usize];
                            let prev = depth[self.entries[bi].state as usize];
                            if cur > prev {
                                best = Some(i);
                            }
                        }
                    }
                }
            }
            if let Some(i) = best {
                let e = self.entries.swap_remove(i);
                Some((e.state, e.trigger))
            } else {
                None
            }
        }
        pub fn min_remaining(&self) -> Option<core::time::Duration> {
            self.entries.iter().map(|e| e.remaining_ns).min().map(|ns| {
                let secs = (ns / 1_000_000_000) as u64;
                let rem = (ns % 1_000_000_000) as u32;
                core::time::Duration::new(secs, rem)
            })
        }
    }

    /// Convert an f64 seconds value to a Duration (runtime, non-const).
    pub fn duration_from_secs_f64(secs: f64) -> core::time::Duration {
        core::time::Duration::from_nanos((secs * 1_000_000_000.0) as u64)
    }

    /// Type-erased push interface over the event queue, so the generated
    /// `ActionContext` does not need to be parameterized by the queue capacity.
    pub trait QueuePush<E> {
        fn push(&mut self, ev: E) -> Result<(), HsmcError>;
    }

    impl<E, const N: usize> QueuePush<E> for heapless::Deque<E, N> {
        fn push(&mut self, ev: E) -> Result<(), HsmcError> {
            self.push_back(ev).map_err(|_| HsmcError::QueueFull)
        }
    }

    /// Proxy used by generated code to route `emit()` pushes through the
    /// internal deque while recording overflow on the machine. When the deque
    /// rejects a push, the `overflow` flag is set and further pushes within
    /// the same tick short-circuit to `Err(QueueFull)` without reaching the
    /// deque. `run()` inspects this flag each iteration and surfaces the
    /// failure rather than letting it be silently swallowed by action code.
    pub struct EmitProxy<'a, E, const N: usize> {
        pub queue: &'a mut heapless::Deque<E, N>,
        pub overflow: &'a mut bool,
    }

    impl<'a, E, const N: usize> QueuePush<E> for EmitProxy<'a, E, N> {
        fn push(&mut self, ev: E) -> Result<(), HsmcError> {
            if *self.overflow {
                return Err(HsmcError::QueueFull);
            }
            match self.queue.push_back(ev) {
                Ok(()) => Ok(()),
                Err(_) => {
                    *self.overflow = true;
                    Err(HsmcError::QueueFull)
                }
            }
        }
    }
}
